wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.8
    framework: huggingface
    huggingface_version: 4.19.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.15
    start_time: 1674330659.236764
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.9.15
      5: 0.13.8
      6: 4.19.2
      8:
      - 5
architecture:
  desc: null
  value: Linear regression vector of 100 high var c elements mapping
'batch_size:':
  desc: null
  value: 750
dataset:
  desc: null
  value: Ghislain reduced ROI of NSD
epochs:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.1
num_workers:
  desc: null
  value: 4
vector:
  desc: null
  value: z
