{
  1: 
    {
      "vdvaeDecoder": 
        {
          "hashNum": "764",
          "vector": "z_vdvae",
          "x_size": 11838
        },
      "clipDecoder":
        {
          "hashNum": "750",
          "vector": "c_img_uc",
          "x_size": 11838
        },
      "clipEncoder": 
        {
          "hashNum": "749",
          "vector": "c_img_uc",
          "x_size": 11838,
          "modelId": "749_model_c_img_uc.pt"
        },
      "clipAutoEncoder": 
        {
          "hashNum": "752",
          "vector": "c_img_uc",
          "x_size": 11838,
          "encoderHash": "749"
        },
      "gnetEncoder": 
        {
          "hashNum": "771",
          "vector": "images",
          "x_size": 11838,
          "modelId": "771_model_images.pt"
        },
      "gnetAutoEncoder":
        {
          "hashNum": "776",
          "vector": "images",
          "x_size": 11838,
          "encoderHash": "771"
        },
      "alexnetEncoder": 
        {
          "hashNum": "579",
          "vector": "alexnet_encoder_sub1",
          "modelId": "alexnet_encoder.pt"
        },
      "alexnetAutoEncoder": 
        {
          "hashNum": "582",
          "vector": "alexnet_encoder_sub1",
          "x_size": 11838,
          "encoderHash": "579"
        },
    },
  2: 
    {
      "vdvaeDecoder": 
        {
          "hashNum": "783",
          "vector": "z_vdvae",
          "x_size": 10325
        },
      "clipDecoder":
        {
          "hashNum": "753",
          "vector": "c_img_uc",
          "x_size": 10325
        },
      "clipEncoder":
        {
          "hashNum": "755",
          "vector": "c_img_uc",
          "x_size": 10325,
          "modelId": "755_model_c_img_uc.pt"
        },
      "clipAutoEncoder":
        {
          "hashNum": "757",
          "vector": "c_img_uc",
          "x_size": 10325,
          "encoderHash": "755"
        },
      "gnetEncoder":
        {
          "hashNum": "772",
          "vector": "images",
          "x_size": 10325,
          "modelId": "772_model_images.pt"
        },
      "gnetAutoEncoder":
        {
          "hashNum": "778",
          "vector": "images",
          "x_size": 10325,
          "encoderHash": "772"
        },
    },
  5: 
    {
      "vdvaeDecoder": 
        {
          "hashNum": "784",
          "vector": "z_vdvae",
          "x_size": 9565
        },
      "clipDecoder":
        {
          "hashNum": "758",
          "vector": "c_img_uc",
          "x_size": 9565
        },
      "clipEncoder":
        {
          "hashNum": "759",
          "vector": "c_img_uc",
          "x_size": 9565,
          "modelId": "759_model_c_img_uc.pt"
        },
      "clipAutoEncoder":
        {
          "hashNum": "760",
          "vector": "c_img_uc",
          "x_size": 9565,
          "encoderHash": "759"
        },
      "gnetEncoder":
        {
          "hashNum": "774",
          "vector": "images",
          "x_size": 9565,
          "modelId": "774_model_images.pt"
        },
      "gnetAutoEncoder":
        {
          "hashNum": "779",
          "vector": "images",
          "x_size": 9565,
          "encoderHash": "774"
        },
    },
  7: 
    {
      "vdvaeDecoder": 
        {
          "hashNum": "785",
          "vector": "z_vdvae",
          "x_size": 9162
        },
      "clipDecoder":
        {
          "hashNum": "761",
          "vector": "c_img_uc",
          "x_size": 9162
        },
      "clipEncoder":
        {
          "hashNum": "762",
          "vector": "c_img_uc",
          "x_size": 9162,
          "modelId": "762_model_c_img_uc.pt"
        },
      "clipAutoEncoder":
        {
          "hashNum": "763",
          "vector": "c_img_uc",
          "x_size": 9162,
          "encoderHash": "762"
        },
      "gnetEncoder":
        {
          "hashNum": "775",
          "vector": "images",
          "x_size": 9162,
          "modelId": "775_model_images.pt"
        },
      "gnetAutoEncoder":
        {
          "hashNum": "780",
          "vector": "images",
          "x_size": 9162,
          "encoderHash": "775"
        },
    },
}