{
  1: 
    {
      "vdvaeDecoder": 
        {
          "hashNum": "797",
          "vector": "z_vdvae",
          "x_size": 15724
        },
      "clipDecoder":
        {
          "hashNum": "792",
          "vector": "c_img_uc",
          "x_size": 15724
        },
      "clipEncoder": 
        {
          "hashNum": "793",
          "vector": "c_img_uc",
          "x_size": 15724,
          "modelId": "793_model_c_img_uc.pt"
        },
      "clipAutoEncoder": 
        {
          "hashNum": "794",
          "vector": "c_img_uc",
          "x_size": 15724,
          "encoderHash": "793"
        },
      "gnetEncoder": 
        {
          "hashNum": "788",
          "vector": "images",
          "x_size": 15724,
          "modelId": "788_model_images.pt"
        },
      "gnetAutoEncoder":
        {
          "hashNum": "796",
          "vector": "images",
          "x_size": 15724,
          "encoderHash": "788"
        },
        "dualEncoder":
        {
          "hashNum": "SCS_gnetEncoder_clipEncoder",
          "vector": "images",
          "x_size": 15724,
          "modelId": "SCS_gnetEncoder_clipEncoder_model_images.pt"
        },
        "dualAutoEncoder":
        {
          "hashNum": "809",
          "vector": "images",
          "x_size": 15724,
          "encoderHash": "SCS_gnetEncoder_clipEncoder"
        },
        #storing the topN parameter for each config
        "LibraryAssembler": 
        {
          "clipEncoder": 200,
          "gnetEncoder": 25,
          "dualGuided": 76
        },
    },
  2: 
    {
      "vdvaeDecoder": 
        {
          "hashNum": "",
          "vector": "z_vdvae",
          "x_size": 14278
        },
      "clipDecoder":
        {
          "hashNum": "",
          "vector": "c_img_uc",
          "x_size": 14278
        },
      "clipEncoder":
        {
          "hashNum": "798",
          "vector": "c_img_uc",
          "x_size": 14278,
          "modelId": "798_model_c_img_uc.pt"
        },
      "clipAutoEncoder":
        {
          "hashNum": "799",
          "vector": "c_img_uc",
          "x_size": 14278,
          "encoderHash": "798"
        },
      "gnetEncoder":
        {
          "hashNum": "789",
          "vector": "images",
          "x_size": 14278,
          "modelId": "789_model_images.pt"
        },
      "gnetAutoEncoder":
        {
          "hashNum": "801",
          "vector": "images",
          "x_size": 14278,
          "encoderHash": "789"
        },
        "dualEncoder":
        {
          "hashNum": "SCS_gnetEncoder_clipEncoder",
          "vector": "images",
          "x_size": 14278,
          "modelId": "SCS_gnetEncoder_clipEncoder_model_images.pt"
        },
        "dualAutoEncoder":
        {
          "hashNum": "810",
          "vector": "images",
          "x_size": 14278,
          "encoderHash": "SCS_gnetEncoder_clipEncoder"
        },
        #storing the topN parameter for each config
        "LibraryAssembler": 
        {
          "clipEncoder": 726,
          "gnetEncoder": 69,
          "dualGuided": 106
        },
    },
  5: 
    {
      "vdvaeDecoder": 
        {
          "hashNum": "",
          "vector": "z_vdvae",
          "x_size": 13039
        },
      "clipDecoder":
        {
          "hashNum": "",
          "vector": "c_img_uc",
          "x_size": 13039
        },
      "clipEncoder":
        {
          "hashNum": "802",
          "vector": "c_img_uc",
          "x_size": 13039,
          "modelId": "802_model_c_img_uc.pt"
        },
      "clipAutoEncoder":
        {
          "hashNum": "803",
          "vector": "c_img_uc",
          "x_size": 13039,
          "encoderHash": "802"
        },
      "gnetEncoder":
        {
          "hashNum": "790",
          "vector": "images",
          "x_size": 13039,
          "modelId": "790_model_images.pt"
        },
      "gnetAutoEncoder":
        {
          "hashNum": "804",
          "vector": "images",
          "x_size": 13039,
          "encoderHash": "790"
        },
        "dualEncoder":
        {
          "hashNum": "SCS_gnetEncoder_clipEncoder",
          "vector": "images",
          "x_size": 13039,
          "modelId": "SCS_gnetEncoder_clipEncoder_model_images.pt"
        },
        "dualAutoEncoder":
        {
          "hashNum": "811",
          "vector": "images",
          "x_size": 13039,
          "encoderHash": "SCS_gnetEncoder_clipEncoder"
        },
        #storing the topN parameter for each config
        "LibraryAssembler": 
        {
          "clipEncoder": 271,
          "gnetEncoder": 125,
          "dualGuided": 86
        },
    },
  7: 
    {
      "vdvaeDecoder": 
        {
          "hashNum": "",
          "vector": "z_vdvae",
          "x_size": 12682
        },
      "clipDecoder":
        {
          "hashNum": "",
          "vector": "c_img_uc",
          "x_size": 12682
        },
      "clipEncoder":
        {
          "hashNum": "805",
          "vector": "c_img_uc",
          "x_size": 12682,
          "modelId": "805_model_c_img_uc.pt"
        },
      "clipAutoEncoder":
        {
          "hashNum": "806",
          "vector": "c_img_uc",
          "x_size": 12682,
          "encoderHash": "805"
        },
      "gnetEncoder":
        {
          "hashNum": "791",
          "vector": "images",
          "x_size": 12682,
          "modelId": "791_model_images.pt"
        },
      "gnetAutoEncoder":
        {
          "hashNum": "807",
          "vector": "images",
          "x_size": 12682,
          "encoderHash": "791"
        },
        "dualEncoder":
        {
          "hashNum": "SCS_gnetEncoder_clipEncoder",
          "vector": "images",
          "x_size": 12682,
          "modelId": "SCS_gnetEncoder_clipEncoder_model_images.pt"
        },
        "dualAutoEncoder":
        {
          "hashNum": "812",
          "vector": "images",
          "x_size": 12682,
          "encoderHash": "SCS_gnetEncoder_clipEncoder"
        },
        #storing the topN parameter for each config
        "LibraryAssembler": 
        {
          "clipEncoder": 998,
          "gnetEncoder": 153,
          "dualGuided": 146
        },
    },
}