name: VB2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - pytorch==1.10.0
  - torchvision=0.11.0
  - cudatoolkit=11.3
  - pip:
      - pyyaml==5.1
      - opencv-python